apiVersion: v1 
kind: Pod 
metadata:
  name: nginx-alpine-volume
spec: 
  volumes:  # the volume is created here
  - name: html 
    emptyDir: {}  # lifecycle tied to Pod
  containers: 
  - name: nginx 
    image: nginx:alpine 
    volumeMounts:   # volume to be used by container, the declaration is inside the container. 
      - name: html 
        mountPath: /usr/share/nginx/html
        readOnly: true 
    resources:
  - name: html-updater 
    image: alpine 
    command: ["/bin/sh", "-c"] 
    args: 
      - while true; do date >> /html/index.html;sleep 10; done 
    resources:
    volumeMounts: 
      - name: html 
        mountPath: /html 


# kubectl apply -f nginx-alpine-emptyDir.pod.yml
# kubectl port-forward nginx-alpine-volume 8080:80